version: '3'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./server/mongo-seed
    links:
      - mongodb

  jserver:
    build: ./server
    links:
      - mongodb
    expose: 
      - "8080"

  client:
    build: ./client
    links:
      - jserver
    restart: always
    expose:
      - "80"

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    links:
      - jserver
      - client
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "8080:8080"

